---
Title: mbrain EDA2
author: Jungha
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##  1. 간편결제 사용자 구분 

#### 기준: 간편결제사용액(결제취소액인 LT02제외하고 결제액인 LT01만 사용) 4달치

  - 4달 전 간편결제 사용자는 최근 이용자가 아니므로 제외
  - 해석의 용이성을 위해 결제취소액을 제외한 결제액만 분석에 사용 

#### 방법: K-Medoids 군집분석

```{r}
#preparing data
#library(caret)
library(tidyverse)

data<-read.csv("C:/Users/JunghaYun/Desktop/최종데이터/5060data.csv", encoding="CP949")

nonuser<-data %>% filter(approval_type_LT01_count==0)
user<-data %>% filter(approval_type_LT01_count>0)
  #nrow(user): 501

#필요패키지 다운
#install.packages(c("cluster", "factoextra"))
#install.packages("fpc")
library(cluster)
library(factoextra)
library(fpc)

#K-Medoids clustering (알아서 k개 정해줌, 결과적으로, heavy, light 두 카테고리로 나뉨)
st<-scale(user$price_sum_by_by_approval_type_LT01)
pamk(st)
med<-pamk(st)
med_core<-med$pamobject
table(med_core$clustering)

#   0   1   2 
# 926 425  76 

user$cluster<-med_core$cluster

#경계값
user %>% group_by(cluster) %>%
  summarise(min=min(price_sum_by_by_approval_type_LT01),
            max=max(price_sum_by_by_approval_type_LT01))

#cluster를 factor에서 숫자로변환
user$cluster<-as.numeric(user$cluster)

# nonuser에 cluster 지정
nonuser$cluster<-0

#dataframe 조인
user.nonuser<-union(user,nonuser)

#csv 파일로 저장 
#write.csv(user.nonuser,file="C:/Users/JunghaYun/desaip/deguri/analysis_by_Yun/5060_3cluster.csv",row.names=FALSE)

```



## 2. 군집별 비교분석 

```{r}
library(tidyverse)
old<-read.csv("C:/Users/JunghaYun/desaip/deguri/analysis/analysis_by_Yun/5060_3cluster.csv")
old$cluster<-as.factor(old$cluster)
table(old$cluster)
View(old)

user<-old %>% filter(cluster!=0)
nonuser<-old %>% filter(cluster==0)


pay_type<-old %>% select(starts_with("approval_type_"),cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.)))) 
#View(pay_type)
pay_type1<-pay_type %>% select( cluster,approval_type_LA_count,cluster,approval_type_LW_count,approval_type_LD_count,approval_type_FA_count,approval_type_LT01_count)
View(pay_type1)
##군집순으로 모든 결제거래 타입 count 증가

  
pay_sum<-old %>% select(starts_with("price_sum"),cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.,na.rm = T)))) 
pay_sum1<-pay_sum %>% select( cluster,price_sum,contains("LW"),contains("LD"),contains("LA"),contains("LT01"))
View(pay_sum1)
##금융거래총액,LW,LD 2>0>1순 vs LT01,LA 2>1>0순 


company<-old %>% select(cluster,starts_with("company_code_PA")) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.),2))) 
criterion<-company%>%select(-cluster)
high_com<-criterion[,colSums(criterion)>1]
view(high_com)
high_com%>%colnames()
# 군집별 평균 간편결제 빈도 합 순위: 삼성페이>페이코, 나머지는 합이 1미만임 
# 2군집 4달간 삼성페이 23건, 페이코 약 5건/ 1군집 약 2건, 1건 
# => 아직 다양한 간편결제가 5060에게 많이 활성화되지 않음


old %>% group_by(cluster) %>%  summarise(age=mean(age),gender=mean(gender))
##나이 적을수록, 남자일수록 heavy user
kruskal.test( age ~ cluster, data = old)
# 군집별 연령 차이 있음 
chisq.test(table(old$cluster,old$gender))
# 군집과 성별 연관있음 


old %>% select(area_name1) %>% table()   
## 5060 패널은 경기도>서울>부산>인천순 거주
  
#old %>% select(cluster,area_name1)%>% group_by(cluster) %>% summarise(n()) 

area<-table(old$cluster,old$area_name1)
area <-as.data.frame.matrix(area)
area %>% select(서울특별시,경기도,부산광역시)
area_p<-round(prop.table(table(old$cluster,old$area_name1),1)*100)
area_p
area_p<-as.data.frame.matrix(area_p)
area_p %>% select(서울특별시,경기도,부산광역시) 
##0&1 군집에서 서울과 경기도에 거주하는 비율 유사, 2군집은 경기도 거주 비율 더 높음

#old %>% select(cluster,area_name1)%>%table() %>% prop.table(1)*100 %>% floor()
 

category<-old %>% select(cluster,starts_with("category_code")) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.,na.rm = T))))
#View(category)
criteria<-category%>%select(-cluster)
high_category<-criteria[,colSums(criteria)>35]
high_category%>%colnames()
high_category
##군집별 카테고리별 결제 빈도를 알아본다.
##기타 > 온라인쇼핑몰 > 식비/외식 > 대형마트 순 
cate_p<-round(category[,-1]/rowSums(category[,-1]),2)
high_cate_p<-cate_p[,colSums(cate_p)>0.2]
high_cate_p
##온라인 쇼핑몰, 식비/외식이 전체건수에서 각각 약 10%, 8% 차지 
##기타제외하고 온라인 쇼핑몰이 가장 큰 건수를 차지한다는 것에서 5060의 간편결제 활성화 가능성이 보임  

brand<-old %>% select(cluster,starts_with("category_group")) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.,na.rm = T))))
crit<-brand%>%select(-cluster)
high_brand<-crit[,colSums(crit)>9]
high_brand
high_brand%>%colnames()
##1:CU, 3:GS25 -> 편의점이 그나마 가장 브랜드 코드에서는 높음 



app<-old %>% select(cluster,ends_with("usagetime")) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.,na.rm = T))))
crite<-app%>%select(-cluster)
high_app<-crite[,colSums(crite)>500000]
View(high_app)

col<-high_app%>%colnames()
col
#test<-old %>% select(cluster,col)
#test
kruskal.test( 메신저_usagetime ~ cluster, data = old) 
kruskal.test( 돈버는.리워드_usagetime ~ cluster, data = old) #집단간 차이 없음 
kruskal.test( 검색포털_usagetime ~ cluster, data = old)
kruskal.test( 멤버십.할인쿠폰_usagetime ~ cluster, data = old)
kruskal.test( 동영상.스트리밍_usagetime ~ cluster, data = old)
kruskal.test( 게임_usagetime ~ cluster, data = old)
#돈버는 리워드 빼고는 집단간 차이 있음


old %>% select(Y0001,cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.)))) 
#old는 평균적으로 핵가족(3,4인) 형태

old %>% select(cluster,Y0001) %>%table()
round(prop.table(table(old$cluster,old$Y0001),1)*100)
family_prop<-as.matrix(round(prop.table(table(old$cluster,old$Y0001),1)*100))
kruskal.test( Y0001 ~ cluster, data = old)
#군집간 가족원수 차이 있음

with_child<-apply(family_prop[,3:5],1,sum)
no_child<-100-with_child
family_size<-as.data.frame(t(rbind(no_child,with_child)))
family_size
#heavyuser의 경우 3인가구 이상이 90%이상-> 자녀와 같이 살아서 간편결제에 더 쉽게 접할 수 있어보임 


old %>% select(Y0008,cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.)))) 
#가구 평균연간소득 5천 ~ 7천(소득 발설하기 싫은 심리 반영한 것일 수 있음)

round(prop.table(table(old$cluster,old$Y0009),1)*100)
fisher.test(table(old$cluster,old$Y0009), simulate.p.value=TRUE)
#군집과 현재 거주 중인 주택의 형태는 연관성이 없다. 


round(prop.table(table(old$cluster,old$Y0010),1)*100)
fisher.test(table(old$cluster,old$Y0010), simulate.p.value=TRUE)
#1 군집에 비해 2군집에서 월세는 낮고 자가가 높은 것을 보아 heavyuser의 재산이 더 많아 보인다. -> 재산이 많을수록 간편결제 이용 올라감  
#군집과 현재 거주 중인 주택의 보유 형태는 연관성이 있다. 


round(prop.table(table(old$cluster,old$H0008),1)*100)
round(prop.table(table(old$cluster,old$H0009),1)*100)
#평균적으로 비행기 탑승횟수 0회: 60%
#0,1군집은 지난 1년간 국내선/국제선 탑승회수 비슷
#2군집은 지난 1년간 국내선/국제선 탑승회수 더 많음 -> 여가를 즐기거나 여유있음
kruskal.test( H0008 ~ cluster, data = old)
kruskal.test( H0009 ~ cluster, data = old)
#군집간 국내선 탑승횟수는 차이 없음, 국제선 탑승회수는 차이 있음 


old %>% select(H0010,cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.),2))) 
#통근자 비율 0<1<2 군집 
#kruskal.test( H0010 ~ cluster, data = old)
chisq.test(table(old$cluster,old$H0010))
#하지만 검정 결과 통근여부와 군집은 연관성이 없다.


old %>% select(H0022,cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.),2))) 
#"현재 자가용 자가 운전비율" 2군집이 가장 높음  
chisq.test(table(old$cluster,old$H0022))
#현재 자가용 자가 운전 여부와 군집은 상관있음

old %>% select(I0025,I0026,I0028,cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.),2))) 
chisq.test(table(old$cluster,old$I0025))
chisq.test(table(old$cluster,old$I0026))
chisq.test(table(old$cluster,old$I0028))
# 모바일쇼핑/해외직구 비율: 0<1<2군집  (인터넷쇼핑은 차이없음)
# 군집과 지난 3개월 간 인터넷 쇼핑 이용 여부는 연관없음
# 군집과 지난 3개월 간 모바일쇼핑/해외직구 이용 여부는 연관있음 


round(prop.table(table(old$cluster,old$J0001),1)*100)
round(prop.table(table(old$cluster,old$J0003),1)*100)
kruskal.test( J0001 ~ cluster, data = old)
kruskal.test( J0003 ~ cluster, data = old)
#인터넷 하루이용시간 군집간 전반적으로 비슷, 군집간 차이 없음

round(prop.table(table(old$cluster,old$J0002),1)*100)
round(prop.table(table(old$cluster,old$J0004),1)*100)
kruskal.test( J0002 ~ cluster, data = old)
kruskal.test( J0004 ~ cluster, data = old)
#스마트폰 평일/주말 기준 하루이용시간 0<1,2군집, 군집간 차이 있음 

old %>% select(J0078,cluster) %>% group_by(cluster) %>% summarise_all(funs((mean(.)))) 
#스마트폰 보유 여부 (거의 1)

old %>% select(J0079,J0080,J0081,cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.),2))) 
##**상위 군집일수록 삼성폰 가진 비율 큼 -> 기기의 중요성 
chisq.test(table(old$cluster,old$J0079))
#디지털기기) 현재 삼성스마트폰 보유 여부와 군집은 연관 있음
chisq.test(table(old$cluster,old$J0080))
#디지털기기) 현재 LG폰 보유 여부와 군집은 연관 있음


round(prop.table(table(old$cluster,old$L0031),1)*100)
fisher.test(table(old$cluster,old$L0031), simulate.p.value=TRUE)
# TV컨텐츠) 주시청 장르(1순위)와 군집은 연관있음 
# 2군집은 드라마, 1군집은 스포츠, 예능, 0군집은 뉴스에서 다른 군집 대비 큰 비율을 보임 -> 간편결제 사용자가 미사용자에 비해 여흥거리나 트렌드에 더 높은 관심이 있을 수 있음  


finanace<-old %>% select(paste0('M00',17:27),cluster) %>% group_by(cluster) %>% summarise_all(funs(round(mean(.),2)))
View(finanace)
chisq.test(table(old$cluster,old$M0017))
chisq.test(table(old$cluster,old$M0020))
chisq.test(table(old$cluster,old$M0022))
fisher.test(table(old$cluster,old$M0024),simulate.p.value=TRUE)
chisq.test(table(old$cluster,old$M0025))
chisq.test(table(old$cluster,old$M0026)) #연관있음 
#지난 1년간 보험가입, 예적금가입, 펀드가입 등의 전반적인 금융생활은 군집과 연관 없음
#금융활동) 지난 1년 간 신규 신용 대출 경험 여부만 연관있고 1>2>0 순 


```

