CREATE TABLE `payments` (
  `panel_id` varchar(32) NOT NULL,
  `gender` char(1),
  `age` char(3),
  `sms_id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `user_sim_number` varchar(50),
  `pattern_id` char(12),
  `category_code` char(5),
  `category_group_code` char(5),
  `rating` char(1),
  `latitude` varchar(50),
  `longitude` varchar(50),
  `address` varchar(100),
  `sms_registration_timestamp` char(17),
  `sms_registration_month` char(6),
  `sms_registration_date` char(8),
  `sms_registration_time` char(6),
  `company_name` varchar(50),
  `company_code` char(7),
  `originating_address` varchar(20),
  `package_name` varchar(50),
  `payment_type` char(2),
  `payment_approval_type` char(4),
  `link_company` varchar(50),
  `link_originating_address` varchar(20),
  `transaction_status` char(2),
  `tel_company` varchar(50),
  `approval_store` varchar(100),
  `approval_store_detail` varchar(200),
  `approval_original_price` float,
  `approval_price` float,
  `approval_unit` varchar(3),
  `approval_real_price` float,
  `accumulated_price` float,
  `residual_limit` float,
  `approval_point` float,
  `point_balance` float,
  `approval_method` int(4),
  `approval_date` varchar(4),
  `approval_time` varchar(4),
  `is_usable_data` char(1),
  `is_from` char(1),
  `data_source` char(2),
  `data_channel` char(3),
  `registration_timestamp` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
