---
title: "프로젝트 중간보고서"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
editor_options:
  chunk_output_type: console
mainfont: NanumGothic
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## 50,60 세대의 간편결제 사용 증대를 위한 방안 제안



### 프로젝트 배경 



### 문제 정의


스마트폰만으로 계좌이체, 물건 구입, 음식 주문 등 기존의 신용카드 기능을 대체하는 모바일 결제가 급증하고 있지만 고연령층의 모바일결제 이용률은 낮다. 이들은 모바일결제 시장에서 소외될 수 있는 디지털 취약계층에 해당하는 것이다. 
      
    <아름씨가 조사한 참고자료 추가해 주세요>

  (참조: 김은비 산업연구원(KIET) 연구원은 2018년 12월 23일 발표한 '국내 모바일 간편결제서비스 현황과 시사점' 보고서)


### 프로젝트 목표 


모바일결제 시장에서 소외될 수 있는 디지털 취약계층 중 고연령층을 대상으로 간편결제회사가 신규 이용을 유인하면서 지속적인 이용을 도모할 수 있는 방안을 제안한다. 구체적으로, 고연령층 간편결제 사용자(heavy user, light user)와 미사용자(non user) 간의 특성차이를 살펴보고 간편결제사가 시행할 수 있는 현 간편결제사용자의 관심사에 따른 마케팅 전략을 제안하고 미사용자를 끌어들일 수 있는 유인책을 제안한다. 또한 간편결제사가 제공할 수 있는 고연령층을 타겟으로 한 은행, 펀드, 보험, 쿠폰, 쇼핑 등 다양한 서비스를 알아낸다. 


### 프로젝트 의미


간편결제회사는 고령화사회에서의 핵심이 되는 신규고객을 유치할 수 있고 고객관리 방안을 강구할 수 있다. 고연령층은 보다 편리하고 맞춤화된 간편결제서비스를 이용하며 삶의 질을 향상시킬 수 있다.


### 분석대상


- 엠브레인 리서치 패널 40세 이상인 약 395,589명 
(참고: 50세 이상은 약 145,049명임) 

-	참고로, 제공받은 [Easypayment/ 간편결제] 데이터를 확인한 결과 고연령층 간편결제사용자는 다음과 같다.

    50세 이상: 1319명, 평균 4달에 60만원가량 결제
    40세 이상-50세미만: 5098명, 평균 4달에 90만원가량 결제



### 활용데이터 (엠브레인 측에서 제공한 데이터 중)


- 간편결제사 정보: 회사이름, 연계 금융사

- 소비자 기본 정보: 성별, 연령, 거주지역, 결혼상태, 학력, 직업

- 소비자 설문 정보

  * Y. 가구: 동거자수, 연소득(가족전체), 주택형태, 주택보유형태(자산예측목적)
  * M. 금융 
    - 지난 1개월 간 이용한 경험이 있는 지불/결제 방식(온라인/모바일, 오프라인), 
    - 지난 1년간 귀하께서 경험한 금융/재테크 관련 활동(보험, 예적금 및 투자, 대출, 기타(기부))
  * F. Health
  * I. Shopping
  * J. Digital Life
  * K. Hobby/Leisure
  * L. Media

- 가맹점 정보: 업종, 브랜드, 위치(위경도), 결제날짜(연월일시간), 거래금액



### 분석방법 


예) Decision tree(타겟변수: 간편결제사용여부(heavy/light/nonuser), 설명변수: 나머지데이터)
 
    <도윤씨 담당파트. 내용 추가해주세요>


### 시장분석


간편결제 시장은 2015년부터 시작된 치열한 경쟁 결과 손에 잡히는 기기와 많은 사용자를 무기로 한 제조사와 플랫폼사인 삼성페이, 네이버페이, 카카오페이, 페이코의 4대 강자 체제로 접어들었다. ICT기업에게 결제시장의 주도권이 넘어가는 모습을 본 기존 금융사인 카드사와 은행은 각각이 연합하여 QR페이를 시작하는 등 후발주자로서 시장에서 경쟁력을 키우려 노력하고 있다. 결국 온라인, 오프라인의 간편한 결제를 기본으로 은행, 펀드, 보험, 쿠폰, 쇼핑 등 다양한 서비스를 제공하는 회사에게 간편결제 시장의 패권은 넘어갈 것이라 전문가들은 자문한다.

    <여태껏 저희가 시장조사한 내용들 중 주제와 연관된 부분 추가해 주세요>
	
    이 외에도 이런 식으로 추가 가능한 내용/사항들, 추가해야 할 사항들 모두 넣어 주셔서 발표분량 채워 주시면 되겠습니다. 수정할 부분 자유롭게 수정해 주셔도 됩니다.

