---
Title: mbrain EDA
author: Jungha
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. 연령별 간편결제 사용 현황 
```{r}

```


2. 간편결제 사용자 구분 
기준: 간편결제사용액 4달치
방법: 군집분석

```{r}

#preparing data
#install.packages("caret")
library(caret)
library(tidyverse)
#grouped by panel_id
data<-read.csv("C:/Users/JunghaYun/Desktop/최종데이터/5060data.csv", encoding="CP949")
#attach(data)

nonuser<-data %>% filter(approval_type_LT01_count==0)
user<-data %>% filter(approval_type_LT01_count>0)

#EDA to see outliers 
#boxplot
min(user$price_sum_by_by_approval_type_LT01)
user %>% ggplot(aes(x=1,y=price_sum_by_by_approval_type_LT01))+ geom_boxplot()+coord_flip()

#k-means clustering, k=2 (only easypay user)
st<-scale(user$price_sum_by_by_approval_type_LT01)
kmeansprice<-kmeans(st, centers=2, iter.max=10000)
kmeansprice$centers
table(kmeansprice$cluster)

#remove outlier of user_df 
user$clusters<-kmeansprice$cluster
user_new<-user %>% filter(clusters!=2)

#clustering again 
st<-scale(user_new$price_sum_by_by_approval_type_LT01)
kmeansprice_new<-kmeans(st, centers=2, iter.max=10000)
kmeansprice_new$centers
table(kmeansprice_new$cluster)
#kmeansprice_new


#k-means clustering, k=3 (only easypay user)
st<-scale(user_new$price_sum_by_by_approval_type_LT01)
kmeansprice<-kmeans(st, centers=3, iter.max=10000)
kmeansprice$centers
#kmeansprice
table(kmeansprice$cluster)

# (ing)
# #visualization
# userprice_cluster <- as.factor(kmeansprice$cluster)
# userprice_cluster
# 
# qplot(panel_id, userprice$lt01sum, colour = userprice$cluster, data = userprice)
# 
# #경계값
# min(userprice$lt01sum[userprice$cluster==1])
# max(userprice$lt01sum[userprice$cluster==1])
# min(userprice$lt01sum[userprice$cluster==2])
# max(userprice$lt01sum[userprice$cluster==2])



```


2. 간편결제 사용자 구분 
기준: 간편결제 사용빈도

```{r}

df<-read.csv("C:/Users/JunghaYun/Desktop/최종데이터/5060data.csv", encoding="CP949")

library(tidyverse)

df1<-df%>%filter(approval_type_LT01_count==0)
df3<-df%>%filter(approval_type_LT01_count>10)

ggplot(df3)+geom_bar(mapping=aes(x=approval_type_LT01_count))



```

